import Link from "next/link";
import type { Metadata } from "next";
import Topbar from "@/components/app/Topbar";
import Hint from "@/components/ui/Hint";
import OverviewTrend from "./OverviewTrend";
import OverviewKpis from "./OverviewKpis";
import PlatformVisibilityCard from "./PlatformVisibilityCard";
import CompetitorSovCard from "./CompetitorSovCard";
import TopSourcesCard from "./TopSourcesCard";
import DemoActionButton from "./DemoActionButton";
import { overviewSpec } from "./report";
import "./page.css";

export const metadata: Metadata = { title: "Overview" };

/* Overview — converted from canvas frame #overview.
   Audit data-coherence fixes: "412/500 used" → "412/1,000 used"; competitor table
   header "Δ 7d" → "Δ 30d". Gemini rows kept verbatim (Settings un-pauses Gemini).
   Topbar Export downloads the whole screen as an executive report (./report.ts):
   the KPI summary with plain-English reads, all three "Performance over time"
   trends as dated tables, the competitor / platform / source tables and the
   week's digest.
   Live filters (F9): the topbar's date range and platform pills now re-slice
   this screen for real — the KPI row (<OverviewKpis>), "Performance over time"
   (<OverviewTrend>), "Visibility by platform", "Competitor share of voice" and
   "Top cited sources" all read the active window, and picking a single platform
   narrows the two cards that have a genuine per-platform fixture. "Last 30
   days · all platforms" renders exactly the numbers this frame shipped. */

export default function Page() {
  return (
    <div className="frame-overview">
      <Topbar crumb="Overview" exportFilename="nike-overview-30d.csv" exportReport={overviewSpec} rangeLive platformLive />
      <div style={{padding:"22px 24px",display:"flex",flexDirection:"column",gap:"16px"}}>
        <OverviewKpis />
        <div style={{display:"grid",gridTemplateColumns:"1fr 372px",gap:"14px"}}>
          <div style={{background:"var(--bg1)",border:"1px solid var(--brd)",borderRadius:"10px",padding:"17px 19px"}}><OverviewTrend /></div>
          <PlatformVisibilityCard />
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 372px",gap:"14px"}}>
          <CompetitorSovCard />
          <TopSourcesCard />
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 372px",gap:"14px"}}>
          <div style={{background:"var(--bg1)",border:"1px solid var(--brd)",borderRadius:"10px",padding:"17px 19px"}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><span style={{display:"flex",alignItems:"center",gap:"6px",fontSize:"13.5px",fontWeight:"600"}}>{"This week, summarized"}<Hint text="Plain summary of the last seven days" /></span><span style={{fontSize:"10.5px",color:"var(--fnt)",fontVariantNumeric:"tabular-nums"}}>{"generated by Answr · Aug 4, 09:00"}</span></div><div style={{fontSize:"13px",color:"var(--mut)",lineHeight:"1.75",marginTop:"10px"}}>{"Visibility rose "}<span style={{color:"#4cb782",fontWeight:"500"}}>{"+2.8pt"}</span>{", led by Google AI Overviews ("}<span style={{color:"#4cb782",fontWeight:"500"}}>{"+4.6"}</span>{") after three new runnersworld.com citations. runnersworld.com passed reddit.com as your top earned source. Product-page citations still trail nike.com/running 5:1 while ClaudeBot stays blocked on /help — action "}<span style={{color:"var(--tx)",fontWeight:"500"}}>{"#87"}</span>{" targets this. One watch item: \"price at full retail\" is trending negative from a stale cached pricing page."}</div></div>
          <div style={{background:"var(--bg1)",border:"1px solid var(--brd)",borderRadius:"10px",padding:"17px 19px"}}><div style={{display:"flex",alignItems:"center",gap:"6px"}}><div style={{fontSize:"13.5px",fontWeight:"600"}}>{"Improve visibility"}</div><Hint text="Quick ways to get mentioned more often" /></div><div style={{display:"flex",flexDirection:"column",gap:"7px",marginTop:"12px",fontSize:"12.5px"}}><DemoActionButton label="Create content" note="Creating content needs a live workspace — this demo is read-only." /><DemoActionButton label="Optimize a page" note="Optimizing pages needs a live workspace — this demo is read-only." /><Link href="/app/actions" style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"9px 12px",background:"var(--bg0)",border:"1px solid var(--brd)",borderRadius:"7px",color:"var(--tx)"}}><span style={{fontWeight:"500"}}>{"Review actions"}</span><span style={{display:"flex",alignItems:"center",gap:"8px"}}><span style={{fontSize:"10.5px",fontWeight:"600",color:"#b3a7f8",background:"rgba(142,124,242,0.16)",borderRadius:"4px",padding:"2px 7px",fontVariantNumeric:"tabular-nums"}}>{"24 open"}</span><span style={{color:"var(--ac)"}}>{"→"}</span></span></Link><Link href="/app/prompts" style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"9px 12px",background:"var(--bg0)",border:"1px solid var(--brd)",borderRadius:"7px",color:"var(--tx)"}}><span style={{fontWeight:"500"}}>{"Manage prompts"}</span><span style={{display:"flex",alignItems:"center",gap:"8px"}}><span style={{fontSize:"10.5px",fontWeight:"600",color:"var(--mut)",border:"1px solid var(--brd)",borderRadius:"4px",padding:"2px 7px",fontVariantNumeric:"tabular-nums"}}>{"412/1,000 used"}</span><span style={{color:"var(--ac)"}}>{"→"}</span></span></Link></div></div>
        </div>
      </div>
    </div>
  );
}
