import Link from "next/link";
import "./login.css";

/* Log in — auto-converted from canvas frame #login. */
export default function Frame() {
  return (
    <div className="frame-login">
      <div style={{background:"var(--bg0)",border:"1px solid var(--brd)",borderRadius:"12px",minHeight:"700px",display:"flex",alignItems:"center",justifyContent:"center",backgroundImage:"radial-gradient(rgba(255,255,255,0.045) 1px,transparent 1px)",backgroundSize:"24px 24px"}}><div style={{width:"380px",background:"var(--bg1)",border:"1px solid var(--brd)",borderRadius:"12px",padding:"32px"}}><div style={{display:"flex",alignItems:"center",gap:"9px"}}><div style={{width:"22px",height:"22px",borderRadius:"6px",background:"linear-gradient(135deg,#a394ff,#6d5ce6)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"12px",fontWeight:"700",color:"#fff"}}>{"A"}</div><div style={{fontSize:"17px",fontWeight:"600"}}>{"Answr"}</div></div><div style={{fontSize:"19px",fontWeight:"600",marginTop:"24px"}}>{"Welcome back"}</div><div style={{fontSize:"13px",color:"var(--mut)",marginTop:"5px"}}>{"Log in to your workspace."}</div><div style={{display:"flex",flexDirection:"column",gap:"10px",marginTop:"22px"}}><div style={{border:"1px solid var(--brd)",borderRadius:"8px",padding:"10px 0",textAlign:"center",fontSize:"13px",fontWeight:"500",background:"var(--bg2)"}}>{"Continue with Google"}</div><div style={{border:"1px solid var(--brd)",borderRadius:"8px",padding:"10px 0",textAlign:"center",fontSize:"13px",fontWeight:"500",background:"var(--bg2)"}}>{"Continue with SSO / SAML"}</div></div><div style={{display:"flex",alignItems:"center",gap:"12px",margin:"20px 0"}}><div style={{flex:"1",height:"1px",background:"var(--brd)"}} /><span style={{fontSize:"10.5px",fontWeight:"400",fontVariantNumeric:"tabular-nums",color:"var(--fnt)"}}>{"OR"}</span><div style={{flex:"1",height:"1px",background:"var(--brd)"}} /></div><div style={{fontSize:"10.5px",fontWeight:"500",fontVariantNumeric:"tabular-nums",color:"var(--fnt)"}}>{"Email"}</div><div style={{border:"1px solid var(--brd)",borderRadius:"8px",background:"var(--bg0)",padding:"10px 12px",fontSize:"13px",color:"var(--mut)",marginTop:"7px"}}>{"dana@solara.io"}</div><div style={{fontSize:"10.5px",fontWeight:"500",fontVariantNumeric:"tabular-nums",color:"var(--fnt)",marginTop:"14px"}}>{"Password"}</div><div style={{border:"1px solid var(--ac)",borderRadius:"8px",background:"var(--bg0)",padding:"10px 12px",fontSize:"13px",marginTop:"7px",display:"flex",justifyContent:"space-between"}}><span>{"••••••••••"}</span><span style={{color:"var(--fnt)",fontSize:"12px"}}>{"Show"}</span></div><div style={{textAlign:"center",fontSize:"13px",fontWeight:"600",color:"#fff",background:"var(--ac)",borderRadius:"8px",padding:"11px 0",marginTop:"20px"}}>{"Log in"}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:"16px",fontSize:"12px"}}><Link href="/login">{"Forgot password?"}</Link><span style={{color:"var(--mut)"}}>{"No account? "}<Link href="/signup">{"Sign up"}</Link></span></div></div></div>
    </div>
  );
}
